# Generated by Django 3.1.5 on 2021-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0003_auto_20210118_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(default='', max_length=100),
        ),
    ]
