# Generated by Django 3.1.5 on 2021-01-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers_all',
            new_name='Answers_alll',
        ),
    ]
