# Generated by Django 3.1.5 on 2021-01-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0002_auto_20210120_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers_alll',
            name='answer_co',
            field=models.CharField(default='', max_length=100),
        ),
    ]
