# Generated by Django 3.1.5 on 2021-01-20 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0003_answers_alll_answer_co'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers_alll',
            name='answer_correct',
        ),
    ]
