# Generated by Django 3.1.5 on 2021-01-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0004_remove_answers_alll_answer_correct'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers_alll',
        ),
    ]
