# Generated by Django 3.1.5 on 2021-01-21 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0006_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
