# Generated by Django 3.1.5 on 2021-01-23 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0007_auto_20210121_0521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='User',
        ),
    ]
