# Generated by Django 3.1.5 on 2021-01-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0008_auto_20210123_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mark',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
