# Generated by Django 3.1.5 on 2021-01-23 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_test', '0009_user_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mark',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
